version: '3.8'

services:
  frontend:
    build: ./client
    ports:
      - '3000:3000'
  backend:
    build: ./server
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./media:/usr/src/media
    environment:
      - MONGO_URL=mongodb://admin:admin@mongo:27017/App  #INIT_DB_USER Y PASSWORD
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - ./database/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongoData:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: App
      INIT_DB_USER: admin
      INIT_DB_PASSWORD: admin
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
volumes:
  mongoData: